/* eslint-disable @typescript-eslint/no-explicit-any */

import {
    ClassicEditor as ClassicEditorBase,
    Essentials,
    Paragraph,
    Heading,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    FontFamily,
    FontSize,
    FontColor,
    FontBackgroundColor,
    Alignment,
    Indent,
    IndentBlock,
    Link,
    List,
    BlockQuote,
    Table,
    TableToolbar,
    Image,
    ImageToolbar,
    ImageCaption,
    ImageStyle,
    ImageResize,
    MediaEmbed,
    Highlight,
    RemoveFormat,
    HorizontalLine,
    PasteFromOffice,
    SourceEditing,
  } from "ckeditor5";
  
  class CustomClassicEditor extends ClassicEditorBase {}
  
  const EditorAny = CustomClassicEditor as any;
  
  EditorAny.builtinPlugins = [
    Essentials,
    Paragraph,
    Heading,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    FontFamily,
    FontSize,
    FontColor,
    FontBackgroundColor,
    Alignment,
    Indent,
    IndentBlock,
    Link,
    List,
    BlockQuote,
    Table,
    TableToolbar,
    Image,
    ImageToolbar,
    ImageCaption,
    ImageStyle,
    ImageResize,
    MediaEmbed,
    Highlight,
    RemoveFormat,
    HorizontalLine,
    PasteFromOffice,
    SourceEditing,
  ];
  
  EditorAny.defaultConfig = {
    licenseKey: "GPL", 
    toolbar: {
      items: [
        "undo",
        "redo",
        "|",
        "heading",
        "|",
        "fontFamily",
        "fontSize",
        "|",
        "bold",
        "italic",
        "underline",
        "strikethrough",
        "|",
        "fontColor",
        "fontBackgroundColor",
        "highlight",
        "removeFormat",
        "|",
        "alignment",
        "|",
        "bulletedList",
        "numberedList",
        "|",
        "outdent",
        "indent",
        "|",
        "link",
        "blockQuote",
        "horizontalLine",
        "insertTable",
        "mediaEmbed",
        "|",
        "sourceEditing",
      ],
      shouldNotGroupWhenFull: true,
    },
    table: { contentToolbar: ["tableColumn", "tableRow", "mergeTableCells"] },
    image: {
      toolbar: [
        "toggleImageCaption",
        "imageTextAlternative",
        "|",
        "imageStyle:inline",
        "imageStyle:block",
        "imageStyle:side",
        "|",
        "resizeImage",
      ],
    },
  };
  
  
  export default CustomClassicEditor;
  