export const calculators = [
    {
        name: "National Insurance",
        slug: "ni",
        description: "Estimate UK NI contributions (Class 1 & 4).",
        icon: "ShieldCheck",
    },
    {
        name: "Employed & Self-Employed",
        slug: "combined-tax",
        description: "Calculate tax when you have both a job and side earnings.",
        icon: "Briefcase",
    },
    {
        name: "Salary After Tax",
        slug: "salary-after-tax",
        description: "Estimate your take-home pay after tax and NI deductions.",
        icon: "Wallet",
    },
    {
        name: "UK Income Tax",
        slug: "income-tax",
        description: "Detailed breakdown of your annual UK income tax bands.",
        icon: "Calculator",
    },
    {
        name: "Pension Tax Relief",
        slug: "pension-tax-relief",
        description: "See how much the government adds to your pension pot.",
        icon: "PiggyBank",
    },
    {
        name: "Child Benefit",
        slug: "child-benefit",
        description: "Estimate support and HICBC charges for high earners.",
        icon: "Baby",
    },
    {
        name: "Late Tax Penalty",
        slug: "late-penalty",
        description: "Calculate late filing fines and interest from HMRC..",
        icon: "AlertTriangle",
    },
    {
        name: "Rental Income Tax",
        slug: "rental-tax",
        description: "Landlord tax calculator for property rental profits.",
        icon: "Home",
    },
    {
        name: "CIS Tax Rebate",
        slug: "cis-rebate",
        description: "Construction Industry Scheme tax refund estimator.",
        icon: "HardHat",
    },
    {
        name: "eBay Tax",
        slug: "ebay-tax",
        description: "Estimate tax on online reselling and side hustles.",
        icon: "ShoppingBag",
    },
    {
        name: "Stamp Duty SDLT",
        slug: "stamp-duty",
        description: "UK property purchase tax (Stamp Duty Land Tax) costs.",
        icon: "Key",
    },
    {
        name: "Uber Income Tax",
        slug: "uber-tax",
        description: "Dedicated calculator for ride-share driver profits and tax.",
        icon: "Car",
    },
    {
        name: "Tax Code Checker",
        slug: "tax-code",
        description: "Decode your HMRC tax code and personal allowance.",
        icon: "Hash",
    },
    {
        name: "Mileage Tax",
        slug: "mileage-tax",
        description: "Calculate tax relief for business miles and travel.",
        icon: "MapPin",
    },
    {
        name: "Dividend Tax",
        slug: "dividend-tax",
        description: "Tax on share dividends and company distributions.",
        icon: "PieChart",
    },
    {
        name: "Crypto Tax",
        slug: "crypto-tax",
        description: "Estimate capital gains tax on cryptocurrency trades.",
        icon: "Bitcoin",
    },
    {
        name: "Corporation Tax",
        slug: "corporation-tax",
        description: "UK limited company profit tax estimator (19-25%).",
        icon: "Building",
    },
];
